# Generated by Django 5.2.11 on 2026-02-23 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_shared",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="post",
            name="is_summarized",
            field=models.BooleanField(default=False),
        ),
    ]
