# Generated by Django 5.2.11 on 2026-02-23 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_post_is_shared_post_is_summarized"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="source_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
