# Generated by Django 5.2.11 on 2026-02-23 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_post_source_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_draft",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="post",
            name="site",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
