# Generated by Django 5.2.11 on 2026-02-23 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_post_is_draft_post_site"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="summary",
            field=models.TextField(blank=True, null=True),
        ),
    ]
