# Generated by Django 5.2.11 on 2026-02-23 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_post_summary"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(default="gpt-4o-mini", max_length=100)),
                (
                    "system_prompt",
                    models.TextField(
                        default="You are a professional cybersecurity analyst. Summarize the following security article in Korean using 3-5 bullet points. Focus on: threat type, affected systems, severity level, and recommended actions. Be concise and professional."
                    ),
                ),
                ("max_tokens", models.PositiveIntegerField(default=500)),
                ("temperature", models.FloatField(default=0.3)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "AI Configuration",
            },
        ),
    ]
