# Generated by Django 5.2.11 on 2026-02-24 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_aiconfig"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aiconfig",
            name="max_tokens",
            field=models.PositiveIntegerField(default=1500),
        ),
        migrations.AlterField(
            model_name="aiconfig",
            name="system_prompt",
            field=models.TextField(
                default='당신은 사이버 보안 전문 분석가입니다. 사용자가 제공하는 보안 관련 뉴스/아티클을 분석하여, 반드시 아래 JSON 스키마에 맞는 유효한 JSON만 출력하세요. 마크다운 코드블록(```), 추가 설명, 서문 없이 JSON 객체 그 자체만 반환해야 합니다.\n\n⚠️ 중요: 아래 스키마의 큰따옴표 안 값들은 모두 형식 예시입니다. 실제 출력 시에는 아티클 내용을 분석하여 의미 있는 텍스트로 반드시 대체해야 합니다. "하위소제목", "소제목", "요점", "세부내용" 등의 예시 텍스트를 그대로 사용하지 마세요.\n\n스키마:\n{\n  "title": "<아티클 내용을 가장 잘 나타내는 한국어 제목>",\n  "brief": "<핵심을 1-2줄로 요약한 문장>",\n  "summary": "<최소 200자 최대 500자 / 1~3개 문단 분량 전체 요약>",\n  "hashtag": ["<#영어키워드1>", "<#영어키워드2>"],\n  "sections": [\n    {\n      "caption": "<해당 섹션 주제를 나타내는 실제 소제목>",\n      "content": [\n        "<실제 요점 1>",\n        "<실제 요점 2>",\n        {\n          "caption": "<필요시에만 사용할 실제 하위 소제목>",\n          "content": ["<실제 세부 내용 1>", "<실제 세부 내용 2>"]\n        }\n      ]\n    }\n  ]\n}\n\n요구사항:\n1. sections는 위협 개요 / 영향받는 시스템 / 공격 방법 / 권고 조치 등 실제 내용에 맞게 구성하세요.\n2. 중첩 섹션(content 내 객체)은 상위 섹션을 세분화할 필요가 있을 때만 사용하세요.\n3. 내용이 부족한 섹션은 생략하세요.\n4. hashtag는 CVE 번호, 위협 유형, 제품명 등 5개 이상 영어로 나열하세요.\n5. 답변은 한국어로 합니다(hashtag 제외).\n6. 모든 문장의 어미는 반드시 \'~니다\' 형식의 한국어 격식체(합쇼체)로 통일합니다. 예: ~됩니다, ~있습니다, ~합니다, ~나타납니다. ~함., ~됨. 등의 비격식체는 절대 사용하지 마세요.'
            ),
        ),
        migrations.CreateModel(
            name="CrawlerSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("url", models.URLField(max_length=500)),
                (
                    "source_type",
                    models.CharField(
                        choices=[("rss", "RSS/Atom"), ("html", "HTML Scraping")],
                        default="rss",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "crawl_interval",
                    models.PositiveIntegerField(
                        default=60, help_text="분 단위 크롤 주기"
                    ),
                ),
                ("last_crawled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "http_method",
                    models.CharField(
                        choices=[("GET", "GET"), ("POST", "POST")],
                        default="GET",
                        max_length=10,
                    ),
                ),
                (
                    "request_headers",
                    models.JSONField(
                        blank=True, default=dict, help_text='{"User-Agent": "..."}'
                    ),
                ),
                (
                    "request_body",
                    models.JSONField(
                        blank=True, default=dict, help_text="POST body JSON"
                    ),
                ),
                (
                    "article_list_selector",
                    models.CharField(
                        blank=True, help_text="기사 목록 CSS 선택자", max_length=300
                    ),
                ),
                (
                    "article_link_selector",
                    models.CharField(
                        blank=True, help_text="링크 CSS 선택자", max_length=300
                    ),
                ),
                (
                    "title_selector",
                    models.CharField(
                        blank=True, help_text="제목 CSS 선택자", max_length=300
                    ),
                ),
                (
                    "content_selector",
                    models.CharField(
                        blank=True, help_text="본문 CSS 선택자", max_length=300
                    ),
                ),
                (
                    "date_selector",
                    models.CharField(
                        blank=True, help_text="날짜 CSS 선택자 (선택)", max_length=300
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="crawler_sources",
                        to="api.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CrawlerLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("playwright_fallback", "Playwright Fallback"),
                            ("error", "Error"),
                        ],
                        max_length=30,
                    ),
                ),
                ("articles_found", models.PositiveIntegerField(default=0)),
                ("articles_created", models.PositiveIntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("crawled_at", models.DateTimeField(auto_now_add=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="api.crawlersource",
                    ),
                ),
            ],
            options={
                "ordering": ["-crawled_at"],
            },
        ),
    ]
