# Generated by Django 5.2.11 on 2026-02-24 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_aiconfig_max_tokens_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="crawlersource",
            name="fetch_full_content",
            field=models.BooleanField(
                default=False, help_text="RSS 피드 항목의 원본 링크를 방문해 전문 수집"
            ),
        ),
        migrations.AddField(
            model_name="crawlersource",
            name="full_content_selector",
            field=models.CharField(
                blank=True, help_text="전문 수집 시 본문 CSS 선택자", max_length=300
            ),
        ),
    ]
