# Generated by Django 5.2.11 on 2026-02-24 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_crawlersource_fetch_full_content_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="crawlersource",
            name="exclude_selectors",
            field=models.TextField(
                blank=True,
                help_text="제거할 CSS 선택자 목록 (쉼표 구분, 예: .ad, #sidebar, .related-articles)",
            ),
        ),
        migrations.AlterField(
            model_name="crawlersource",
            name="fetch_full_content",
            field=models.BooleanField(
                default=False, help_text="각 기사 URL에 접속하여 전문 수집"
            ),
        ),
    ]
