# Generated by Django 5.2.11 on 2026-02-24 08:27

from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_crawlersource_exclude_selectors_and_more"),
    ]

    operations = [
        VectorExtension(),
    ]
