# Generated by Django 5.2.11 on 2026-02-24 08:43

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_enable_pgvector"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="embedding",
            field=pgvector.django.vector.VectorField(
                blank=True, dimensions=1536, null=True
            ),
        ),
    ]
