# Generated by Django 5.2.11 on 2026-02-24 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_add_post_embedding"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="parent_post",
            field=models.ForeignKey(
                blank=True,
                help_text="동일한 이슈로 판단된 대표 기사",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="related_posts",
                to="api.post",
            ),
        ),
    ]
