# Generated by Django 5.2.11 on 2026-02-25 04:15

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension

class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_add_post_parent"),
    ]

    operations = [
        TrigramExtension(),
    ]
