# Generated by Django 5.2.11 on 2026-02-25 04:18

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_enable_pg_trgm"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="post",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["title"], name="api_post_title_gin", opclasses=["gin_trgm_ops"]
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["content"],
                name="api_post_content_gin",
                opclasses=["gin_trgm_ops"],
            ),
        ),
    ]
