# Generated by Django 5.2.11 on 2026-02-25 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_post_api_post_title_gin_post_api_post_content_gin"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="iocs",
            field=models.JSONField(
                blank=True, default=list, help_text="추출된 외부 링크/IP/도메인 목록"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="published_at",
            field=models.DateTimeField(
                blank=True, help_text="실제 기사 발행일", null=True
            ),
        ),
    ]
