# Generated by Django 5.2.11 on 2026-02-25 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_post_iocs_post_published_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="aiconfig",
            name="similarity_threshold",
            field=models.FloatField(
                default=0.2,
                help_text="이슈 그룹화 코사인 거리 임계값 (작을수록 엄격함)",
            ),
        ),
    ]
