# Generated by Django 5.2.11 on 2026-02-26 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_aiconfig_similarity_threshold"),
    ]

    operations = [
        migrations.AddField(
            model_name="aiconfig",
            name="telegram_bot_token",
            field=models.CharField(
                blank=True,
                help_text="텔레그램 봇 토큰 (가이드/권고문 알림용)",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="aiconfig",
            name="telegram_chat_id",
            field=models.CharField(
                blank=True, help_text="알림을 받을 채팅방 ID", max_length=100
            ),
        ),
    ]
