# Generated by Django 5.2.11 on 2026-03-19 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_aiconfig_telegram_bot_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="crawlerlog",
            name="attempt_count",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="crawlerlog",
            name="duration_seconds",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="crawlerlog",
            name="triggered_by",
            field=models.CharField(
                choices=[("manual", "Manual"), ("scheduled", "Scheduled")],
                default="manual",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="crawlersource",
            name="auto_disable_after_failures",
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name="crawlersource",
            name="consecutive_failures",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="crawlersource",
            name="is_running",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="crawlersource",
            name="last_error_message",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="crawlersource",
            name="last_run_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="crawlersource",
            name="last_status",
            field=models.CharField(
                choices=[
                    ("idle", "Idle"),
                    ("success", "Success"),
                    ("playwright_fallback", "Playwright Fallback"),
                    ("error", "Error"),
                ],
                default="idle",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="crawlersource",
            name="last_success_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="crawlersource",
            name="max_retries",
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name="crawlersource",
            name="retry_backoff_minutes",
            field=models.PositiveIntegerField(default=10),
        ),
    ]
