# Generated by Django 5.2.11 on 2026-03-23 01:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_crawlerlog_attempt_count_crawlerlog_duration_seconds_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CrawlRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "triggered_by",
                    models.CharField(
                        choices=[("manual", "Manual"), ("scheduled", "Scheduled")],
                        default="manual",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("success", "Success"),
                            ("playwright_fallback", "Playwright Fallback"),
                            ("error", "Error"),
                        ],
                        default="running",
                        max_length=30,
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("attempt_count", models.PositiveSmallIntegerField(default=0)),
                ("articles_found", models.PositiveIntegerField(default=0)),
                ("articles_created", models.PositiveIntegerField(default=0)),
                ("duplicate_count", models.PositiveIntegerField(default=0)),
                ("filtered_count", models.PositiveIntegerField(default=0)),
                ("error_count", models.PositiveIntegerField(default=0)),
                ("duration_seconds", models.PositiveIntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="api.crawlersource",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="CrawlItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("duplicate", "Duplicate"),
                            ("filtered", "Filtered"),
                            ("error", "Error"),
                        ],
                        max_length=20,
                    ),
                ),
                ("source_url", models.URLField(blank=True, max_length=500)),
                ("normalized_url", models.URLField(blank=True, max_length=500)),
                ("title", models.CharField(blank=True, max_length=255)),
                ("error_message", models.TextField(blank=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="crawl_items",
                        to="api.post",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="api.crawlrun",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
