# Generated by Django 5.2.11 on 2026-03-23 02:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_post_status(apps, schema_editor):
    Post = apps.get_model("api", "Post")
    Post.objects.filter(is_draft=True).update(status="draft")
    Post.objects.filter(is_draft=False).update(status="published")


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0020_crawlrun_crawlitem"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="approval_requested_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_posts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="rejected_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="rejected_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rejected_posts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="rejection_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("review", "In Review"),
                    ("rejected", "Rejected"),
                    ("published", "Published"),
                    ("archived", "Archived"),
                ],
                default="published",
                max_length=20,
            ),
        ),
        migrations.RunPython(backfill_post_status, migrations.RunPython.noop),
    ]
