# Generated by Django 5.2.11 on 2026-03-25 00:00

from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_post_approval_requested_at_post_approved_at_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='post',
            index=models.Index(
                fields=['source_url'],
                name='api_post_source_url_idx',
                condition=Q(source_url__isnull=False) & ~Q(source_url=''),
            ),
        ),
    ]
