# Generated by Django 5.2.11 on 2026-03-25 00:30

from urllib.parse import parse_qsl, urlencode, urlparse, urlunparse

from django.db import migrations, models
from django.db.models import Q


def normalize_source_url(value: str) -> str:
    raw = (value or '').strip()
    if not raw:
        return ''

    parsed = urlparse(raw)
    if not parsed.scheme or not parsed.netloc:
        return raw

    scheme = parsed.scheme.lower()
    hostname = (parsed.hostname or '').lower()
    port = parsed.port

    if (scheme == 'http' and port == 80) or (scheme == 'https' and port == 443):
        port = None

    netloc = hostname
    if port:
        netloc = f'{hostname}:{port}'

    path = parsed.path or '/'
    if path != '/' and path.endswith('/'):
        path = path.rstrip('/')

    tracking_keys = {
        'fbclid',
        'gclid',
        'mc_cid',
        'mc_eid',
        'mkt_tok',
        '_hsenc',
        '_hsmi',
    }
    query_items = [
        (key, val)
        for key, val in parse_qsl(parsed.query, keep_blank_values=True)
        if not key.lower().startswith('utm_') and key.lower() not in tracking_keys
    ]
    query = urlencode(sorted(query_items))

    return urlunparse((scheme, netloc, path, '', query, ''))


def backfill_normalized_source_url(apps, schema_editor):
    Post = apps.get_model('api', 'Post')
    for post in Post.objects.exclude(source_url__isnull=True).exclude(source_url='').iterator():
        post.normalized_source_url = normalize_source_url(post.source_url)
        post.save(update_fields=['normalized_source_url'])


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_post_source_url_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='normalized_source_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.RunPython(backfill_normalized_source_url, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(
                fields=['normalized_source_url'],
                name='api_post_norm_source_url_idx',
                condition=Q(normalized_source_url__isnull=False) & ~Q(normalized_source_url=''),
            ),
        ),
    ]
