# Generated by Django 5.2.11 on 2026-03-25 02:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0023_post_normalized_source_url"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="post",
            name="api_post_norm_source_url_idx",
        ),
        migrations.AddConstraint(
            model_name="post",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("normalized_source_url__isnull", False),
                    models.Q(("normalized_source_url", ""), _negated=True),
                ),
                fields=("normalized_source_url",),
                name="api_post_norm_source_url_uniq",
            ),
        ),
    ]
