# Generated by Django 5.2.11 on 2026-03-25 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0024_remove_post_api_post_norm_source_url_idx_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="crawlerlog",
            index=models.Index(
                fields=["source", "-crawled_at"], name="api_clog_source_crawled_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="crawlerlog",
            index=models.Index(fields=["-crawled_at"], name="api_clog_crawled_idx"),
        ),
        migrations.AddIndex(
            model_name="crawlersource",
            index=models.Index(
                fields=["is_active", "is_running", "last_crawled_at", "created_at"],
                name="api_csrc_sched_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="crawlitem",
            index=models.Index(
                fields=["run", "item_status"], name="api_citem_run_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="crawlrun",
            index=models.Index(
                fields=["source", "-started_at"], name="api_crun_source_started_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="crawlrun",
            index=models.Index(fields=["-started_at"], name="api_crun_started_idx"),
        ),
    ]
