# Generated by Django 5.2.11 on 2026-03-25 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0025_crawlerlog_api_clog_source_crawled_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CveRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cve_id", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
                ("severity", models.CharField(blank=True, max_length=20)),
                ("cvss_score", models.FloatField(blank=True, null=True)),
                ("published_date", models.DateField(blank=True, null=True)),
                ("vendor", models.CharField(blank=True, max_length=255)),
                ("product", models.CharField(blank=True, max_length=255)),
                ("is_tracked", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                ("mention_count", models.PositiveIntegerField(default=0)),
                ("first_seen", models.DateTimeField(blank=True, null=True)),
                ("last_seen", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-mention_count", "-last_seen", "cve_id"],
                "indexes": [
                    models.Index(
                        fields=["severity", "-last_seen"],
                        name="api_cve_severity_seen_idx",
                    ),
                    models.Index(
                        fields=["is_tracked", "-last_seen"],
                        name="api_cve_tracked_seen_idx",
                    ),
                    models.Index(
                        fields=["-mention_count", "-last_seen"],
                        name="api_cve_mentions_seen_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PostCveMention",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mentioned_in",
                    models.CharField(
                        choices=[
                            ("title", "Title"),
                            ("content", "Content"),
                            ("both", "Both"),
                        ],
                        default="content",
                        max_length=20,
                    ),
                ),
                ("legacy_reference_ids", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cve",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_mentions",
                        to="api.cverecord",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cve_mentions",
                        to="api.post",
                    ),
                ),
            ],
            options={
                "ordering": ["cve__cve_id"],
                "indexes": [
                    models.Index(fields=["post"], name="api_postcve_post_idx"),
                    models.Index(
                        fields=["cve", "-created_at"],
                        name="api_postcve_cve_created_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("post", "cve"), name="api_post_cve_unique"
                    )
                ],
            },
        ),
    ]
