# Generated by Django 5.2.11 on 2026-03-25 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0026_cverecord_postcvemention"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="postcvemention",
            name="api_postcve_post_idx",
        ),
        migrations.AddField(
            model_name="postcvemention",
            name="source",
            field=models.CharField(
                choices=[
                    ("legacy_import", "Legacy Import"),
                    ("auto_extract", "Auto Extract"),
                    ("manual", "Manual"),
                ],
                default="legacy_import",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="postcvemention",
            index=models.Index(
                fields=["post", "source"], name="api_postcve_post_source_idx"
            ),
        ),
    ]
